### ISSUE TITLE
Fix repo url

### ISSUE THREAD

**Issue by waldyrious** [luiscruz/google_play_reader#1]
The url in the main page of this repo points to your personal page. Is this deliberate? The usual expectation is that it points to a page specific to the project. (You can always leave it empty if there's no such page.)

**Comment by luiscruz** [comment]
I guess you're right Waldir 👍 
I've just fixed that.
Anyway feel free to come up with a website for the project 😝

**Comment by waldyrious** [comment]
If you fill the README with some more info, I'd have at least some material to work with :P

**Comment by waldyrious** [comment]
> If you fill the README with some more info

Oh wait, you did already :-| haha

Well, you can try activating the GitHub Pages feature in the repository settings. IIRC just doing that will render the README nicely as HTML at http://luiscruz.github.io/google_play_reader.

**Comment by luiscruz** [comment]
Cool I didn't know that. Just did it! Thanks!

**Comment by waldyrious** [comment]
It's a [relatively recent feature](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3) :)
